// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.dianping.dpsf.example.protobuf;

public final class DPSFExample {
  private DPSFExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Parameter extends
      com.google.protobuf.GeneratedMessage {
    // Use Parameter.newBuilder() to construct.
    private Parameter() {
      initFields();
    }
    private Parameter(boolean noInit) {}
    
    private static final Parameter defaultInstance;
    public static Parameter getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parameter getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.example.protobuf.DPSFExample.internal_static_com_dianping_dpsf_example_protobuf_Parameter_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.example.protobuf.DPSFExample.internal_static_com_dianping_dpsf_example_protobuf_Parameter_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int32 age = 2;
    public static final int AGE_FIELD_NUMBER = 2;
    private boolean hasAge;
    private int age_ = 0;
    public boolean hasAge() { return hasAge; }
    public int getAge() { return age_; }
    
    // repeated string book = 3;
    public static final int BOOK_FIELD_NUMBER = 3;
    private java.util.List<java.lang.String> book_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getBookList() {
      return book_;
    }
    public int getBookCount() { return book_.size(); }
    public java.lang.String getBook(int index) {
      return book_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasAge()) {
        output.writeInt32(2, getAge());
      }
      for (java.lang.String element : getBookList()) {
        output.writeString(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasAge()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getAge());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getBookList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getBookList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.example.protobuf.DPSFExample.Parameter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.example.protobuf.DPSFExample.Parameter result;
      
      // Construct using com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.example.protobuf.DPSFExample.Parameter();
        return builder;
      }
      
      protected com.dianping.dpsf.example.protobuf.DPSFExample.Parameter internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.example.protobuf.DPSFExample.Parameter();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDescriptor();
      }
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.Parameter getDefaultInstanceForType() {
        return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.example.protobuf.DPSFExample.Parameter build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.example.protobuf.DPSFExample.Parameter buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.Parameter buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.book_ != java.util.Collections.EMPTY_LIST) {
          result.book_ =
            java.util.Collections.unmodifiableList(result.book_);
        }
        com.dianping.dpsf.example.protobuf.DPSFExample.Parameter returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.example.protobuf.DPSFExample.Parameter) {
          return mergeFrom((com.dianping.dpsf.example.protobuf.DPSFExample.Parameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.example.protobuf.DPSFExample.Parameter other) {
        if (other == com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (!other.book_.isEmpty()) {
          if (result.book_.isEmpty()) {
            result.book_ = new java.util.ArrayList<java.lang.String>();
          }
          result.book_.addAll(other.book_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 16: {
              setAge(input.readInt32());
              break;
            }
            case 26: {
              addBook(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional int32 age = 2;
      public boolean hasAge() {
        return result.hasAge();
      }
      public int getAge() {
        return result.getAge();
      }
      public Builder setAge(int value) {
        result.hasAge = true;
        result.age_ = value;
        return this;
      }
      public Builder clearAge() {
        result.hasAge = false;
        result.age_ = 0;
        return this;
      }
      
      // repeated string book = 3;
      public java.util.List<java.lang.String> getBookList() {
        return java.util.Collections.unmodifiableList(result.book_);
      }
      public int getBookCount() {
        return result.getBookCount();
      }
      public java.lang.String getBook(int index) {
        return result.getBook(index);
      }
      public Builder setBook(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.book_.set(index, value);
        return this;
      }
      public Builder addBook(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.book_.isEmpty()) {
          result.book_ = new java.util.ArrayList<java.lang.String>();
        }
        result.book_.add(value);
        return this;
      }
      public Builder addAllBook(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.book_.isEmpty()) {
          result.book_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.book_);
        return this;
      }
      public Builder clearBook() {
        result.book_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.example.protobuf.Parameter)
    }
    
    static {
      defaultInstance = new Parameter(true);
      com.dianping.dpsf.example.protobuf.DPSFExample.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.example.protobuf.Parameter)
  }
  
  public static final class ReturnValue extends
      com.google.protobuf.GeneratedMessage {
    // Use ReturnValue.newBuilder() to construct.
    private ReturnValue() {
      initFields();
    }
    private ReturnValue(boolean noInit) {}
    
    private static final ReturnValue defaultInstance;
    public static ReturnValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReturnValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.example.protobuf.DPSFExample.internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.example.protobuf.DPSFExample.internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_fieldAccessorTable;
    }
    
    // required int32 money = 1;
    public static final int MONEY_FIELD_NUMBER = 1;
    private boolean hasMoney;
    private int money_ = 0;
    public boolean hasMoney() { return hasMoney; }
    public int getMoney() { return money_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMoney) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMoney()) {
        output.writeInt32(1, getMoney());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMoney());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue result;
      
      // Construct using com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue();
        return builder;
      }
      
      protected com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDescriptor();
      }
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue getDefaultInstanceForType() {
        return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue) {
          return mergeFrom((com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue other) {
        if (other == com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance()) return this;
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMoney(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 money = 1;
      public boolean hasMoney() {
        return result.hasMoney();
      }
      public int getMoney() {
        return result.getMoney();
      }
      public Builder setMoney(int value) {
        result.hasMoney = true;
        result.money_ = value;
        return this;
      }
      public Builder clearMoney() {
        result.hasMoney = false;
        result.money_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.example.protobuf.ReturnValue)
    }
    
    static {
      defaultInstance = new ReturnValue(true);
      com.dianping.dpsf.example.protobuf.DPSFExample.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.example.protobuf.ReturnValue)
  }
  
  public static abstract class ExampleService
      implements com.google.protobuf.Service {
    protected ExampleService() {}
    
    public interface Interface {
      public abstract void getMoney(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done);
      
      public abstract void test(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ExampleService() {
        @Override
        public  void getMoney(
            com.google.protobuf.RpcController controller,
            com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
            com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done) {
          impl.getMoney(controller, request, done);
        }
        
        @Override
        public  void test(
            com.google.protobuf.RpcController controller,
            com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
            com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done) {
          impl.test(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getMoney(controller, (com.dianping.dpsf.example.protobuf.DPSFExample.Parameter)request);
            case 1:
              return impl.test(controller, (com.dianping.dpsf.example.protobuf.DPSFExample.Parameter)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance();
            case 1:
              return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance();
            case 1:
              return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void getMoney(
        com.google.protobuf.RpcController controller,
        com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
        com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done);
    
    public abstract void test(
        com.google.protobuf.RpcController controller,
        com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
        com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.dianping.dpsf.example.protobuf.DPSFExample.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getMoney(controller, (com.dianping.dpsf.example.protobuf.DPSFExample.Parameter)request,
            com.google.protobuf.RpcUtil.<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue>specializeCallback(
              done));
          return;
        case 1:
          this.test(controller, (com.dianping.dpsf.example.protobuf.DPSFExample.Parameter)request,
            com.google.protobuf.RpcUtil.<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance();
        case 1:
          return com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance();
        case 1:
          return com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.dianping.dpsf.example.protobuf.DPSFExample.ExampleService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void getMoney(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.class,
            com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance()));
      }
      
      public  void test(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.class,
            com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue getMoney(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request)
          throws com.google.protobuf.ServiceException;
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue test(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue getMoney(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request)
          throws com.google.protobuf.ServiceException {
        return (com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance());
      }
      
      
      public com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue test(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.example.protobuf.DPSFExample.Parameter request)
          throws com.google.protobuf.ServiceException {
        return (com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_example_protobuf_Parameter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_example_protobuf_Parameter_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\"com.dianping.dpsf.examp" +
      "le.protobuf\"4\n\tParameter\022\014\n\004name\030\001 \002(\t\022\013" +
      "\n\003age\030\002 \001(\005\022\014\n\004book\030\003 \003(\t\"\034\n\013ReturnValue" +
      "\022\r\n\005money\030\001 \002(\0052\344\001\n\016ExampleService\022j\n\010ge" +
      "tMoney\022-.com.dianping.dpsf.example.proto" +
      "buf.Parameter\032/.com.dianping.dpsf.exampl" +
      "e.protobuf.ReturnValue\022f\n\004test\022-.com.dia" +
      "nping.dpsf.example.protobuf.Parameter\032/." +
      "com.dianping.dpsf.example.protobuf.Retur" +
      "nValueB1\n\"com.dianping.dpsf.example.prot",
      "obufB\013DPSFExample"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dianping_dpsf_example_protobuf_Parameter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dianping_dpsf_example_protobuf_Parameter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_example_protobuf_Parameter_descriptor,
              new java.lang.String[] { "Name", "Age", "Book", },
              com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.class,
              com.dianping.dpsf.example.protobuf.DPSFExample.Parameter.Builder.class);
          internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_example_protobuf_ReturnValue_descriptor,
              new java.lang.String[] { "Money", },
              com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.class,
              com.dianping.dpsf.example.protobuf.DPSFExample.ReturnValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
