// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dpsf-test.proto

package com.dianping.dpsf.protocol.protobuf;

public final class DpsfTestMessages {
  private DpsfTestMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CreateOrderRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateOrderRequest.newBuilder() to construct.
    private CreateOrderRequest() {
      initFields();
    }
    private CreateOrderRequest(boolean noInit) {}
    
    private static final CreateOrderRequest defaultInstance;
    public static CreateOrderRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateOrderRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_fieldAccessorTable;
    }
    
    // optional string productName = 1;
    public static final int PRODUCTNAME_FIELD_NUMBER = 1;
    private boolean hasProductName;
    private java.lang.String productName_ = "";
    public boolean hasProductName() { return hasProductName; }
    public java.lang.String getProductName() { return productName_; }
    
    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProductName()) {
        output.writeString(1, getProductName());
      }
      if (hasCount()) {
        output.writeInt32(2, getCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProductName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getProductName());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.getDefaultInstance()) return this;
        if (other.hasProductName()) {
          setProductName(other.getProductName());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setProductName(input.readString());
              break;
            }
            case 16: {
              setCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string productName = 1;
      public boolean hasProductName() {
        return result.hasProductName();
      }
      public java.lang.String getProductName() {
        return result.getProductName();
      }
      public Builder setProductName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProductName = true;
        result.productName_ = value;
        return this;
      }
      public Builder clearProductName() {
        result.hasProductName = false;
        result.productName_ = getDefaultInstance().getProductName();
        return this;
      }
      
      // optional int32 count = 2;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.CreateOrderRequest)
    }
    
    static {
      defaultInstance = new CreateOrderRequest(true);
      com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.CreateOrderRequest)
  }
  
  public static final class CreateOrderResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use CreateOrderResponse.newBuilder() to construct.
    private CreateOrderResponse() {
      initFields();
    }
    private CreateOrderResponse(boolean noInit) {}
    
    private static final CreateOrderResponse defaultInstance;
    public static CreateOrderResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateOrderResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_fieldAccessorTable;
    }
    
    // required bool succeed = 1;
    public static final int SUCCEED_FIELD_NUMBER = 1;
    private boolean hasSucceed;
    private boolean succeed_ = false;
    public boolean hasSucceed() { return hasSucceed; }
    public boolean getSucceed() { return succeed_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSucceed) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSucceed()) {
        output.writeBool(1, getSucceed());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSucceed()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getSucceed());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance()) return this;
        if (other.hasSucceed()) {
          setSucceed(other.getSucceed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSucceed(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required bool succeed = 1;
      public boolean hasSucceed() {
        return result.hasSucceed();
      }
      public boolean getSucceed() {
        return result.getSucceed();
      }
      public Builder setSucceed(boolean value) {
        result.hasSucceed = true;
        result.succeed_ = value;
        return this;
      }
      public Builder clearSucceed() {
        result.hasSucceed = false;
        result.succeed_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.CreateOrderResponse)
    }
    
    static {
      defaultInstance = new CreateOrderResponse(true);
      com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.CreateOrderResponse)
  }
  
  public static final class Order extends
      com.google.protobuf.GeneratedMessage {
    // Use Order.newBuilder() to construct.
    private Order() {
      initFields();
    }
    private Order(boolean noInit) {}
    
    private static final Order defaultInstance;
    public static Order getDefaultInstance() {
      return defaultInstance;
    }
    
    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_Order_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_Order_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string productName = 2;
    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private boolean hasProductName;
    private java.lang.String productName_ = "";
    public boolean hasProductName() { return hasProductName; }
    public java.lang.String getProductName() { return productName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasProductName()) {
        output.writeString(2, getProductName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasProductName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getProductName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasProductName()) {
          setProductName(other.getProductName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setProductName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string productName = 2;
      public boolean hasProductName() {
        return result.hasProductName();
      }
      public java.lang.String getProductName() {
        return result.getProductName();
      }
      public Builder setProductName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProductName = true;
        result.productName_ = value;
        return this;
      }
      public Builder clearProductName() {
        result.hasProductName = false;
        result.productName_ = getDefaultInstance().getProductName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.Order)
    }
    
    static {
      defaultInstance = new Order(true);
      com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.Order)
  }
  
  public static final class OrderID extends
      com.google.protobuf.GeneratedMessage {
    // Use OrderID.newBuilder() to construct.
    private OrderID() {
      initFields();
    }
    private OrderID(boolean noInit) {}
    
    private static final OrderID defaultInstance;
    public static OrderID getDefaultInstance() {
      return defaultInstance;
    }
    
    public OrderID getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.OrderID)
    }
    
    static {
      defaultInstance = new OrderID(true);
      com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.OrderID)
  }
  
  public static abstract class OrderService
      implements com.google.protobuf.Service {
    protected OrderService() {}
    
    public interface Interface {
      public abstract void createOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse> done);
      
      public abstract void getOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new OrderService() {
        @Override
        public  void createOrder(
            com.google.protobuf.RpcController controller,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request,
            com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse> done) {
          impl.createOrder(controller, request, done);
        }
        
        @Override
        public  void getOrder(
            com.google.protobuf.RpcController controller,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request,
            com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order> done) {
          impl.getOrder(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.createOrder(controller, (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest)request);
            case 1:
              return impl.getOrder(controller, (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.getDefaultInstance();
            case 1:
              return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance();
            case 1:
              return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void createOrder(
        com.google.protobuf.RpcController controller,
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request,
        com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse> done);
    
    public abstract void getOrder(
        com.google.protobuf.RpcController controller,
        com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request,
        com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.createOrder(controller, (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest)request,
            com.google.protobuf.RpcUtil.<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse>specializeCallback(
              done));
          return;
        case 1:
          this.getOrder(controller, (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID)request,
            com.google.protobuf.RpcUtil.<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.getDefaultInstance();
        case 1:
          return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance();
        case 1:
          return com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void createOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.class,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance()));
      }
      
      public  void getOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request,
          com.google.protobuf.RpcCallback<com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.class,
            com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse createOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request)
          throws com.google.protobuf.ServiceException;
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order getOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse createOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.getDefaultInstance());
      }
      
      
      public com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order getOrder(
          com.google.protobuf.RpcController controller,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID request)
          throws com.google.protobuf.ServiceException {
        return (com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_Order_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dpsf-test.proto\022#com.dianping.dpsf.pro" +
      "tocol.protobuf\"8\n\022CreateOrderRequest\022\023\n\013" +
      "productName\030\001 \001(\t\022\r\n\005count\030\002 \001(\005\"&\n\023Crea" +
      "teOrderResponse\022\017\n\007succeed\030\001 \002(\010\"(\n\005Orde" +
      "r\022\n\n\002id\030\001 \002(\005\022\023\n\013productName\030\002 \001(\t\"\025\n\007Or" +
      "derID\022\n\n\002id\030\001 \002(\0052\367\001\n\014OrderService\022\200\001\n\013c" +
      "reateOrder\0227.com.dianping.dpsf.protocol." +
      "protobuf.CreateOrderRequest\0328.com.dianpi" +
      "ng.dpsf.protocol.protobuf.CreateOrderRes" +
      "ponse\022d\n\010getOrder\022,.com.dianping.dpsf.pr",
      "otocol.protobuf.OrderID\032*.com.dianping.d" +
      "psf.protocol.protobuf.OrderB7\n#com.dianp" +
      "ing.dpsf.protocol.protobufB\020DpsfTestMess" +
      "ages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderRequest_descriptor,
              new java.lang.String[] { "ProductName", "Count", },
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.class,
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderRequest.Builder.class);
          internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_CreateOrderResponse_descriptor,
              new java.lang.String[] { "Succeed", },
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.class,
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.CreateOrderResponse.Builder.class);
          internal_static_com_dianping_dpsf_protocol_protobuf_Order_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_dianping_dpsf_protocol_protobuf_Order_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_Order_descriptor,
              new java.lang.String[] { "Id", "ProductName", },
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.class,
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.Order.Builder.class);
          internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_OrderID_descriptor,
              new java.lang.String[] { "Id", },
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.class,
              com.dianping.dpsf.protocol.protobuf.DpsfTestMessages.OrderID.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
