// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dpsf.proto

package com.dianping.dpsf.protocol.protobuf;

public final class DPSFProtos {
  private DPSFProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DPSFProtos.internal_static_com_dianping_dpsf_protocol_protobuf_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DPSFProtos.internal_static_com_dianping_dpsf_protocol_protobuf_Request_fieldAccessorTable;
    }
    
    // required int32 messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private boolean hasMessageType;
    private int messageType_ = 0;
    public boolean hasMessageType() { return hasMessageType; }
    public int getMessageType() { return messageType_; }
    
    // optional int32 callType = 2;
    public static final int CALLTYPE_FIELD_NUMBER = 2;
    private boolean hasCallType;
    private int callType_ = 0;
    public boolean hasCallType() { return hasCallType; }
    public int getCallType() { return callType_; }
    
    // required int64 transferId = 3;
    public static final int TRANSFERID_FIELD_NUMBER = 3;
    private boolean hasTransferId;
    private long transferId_ = 0L;
    public boolean hasTransferId() { return hasTransferId; }
    public long getTransferId() { return transferId_; }
    
    // optional string rpcVersion = 4;
    public static final int RPCVERSION_FIELD_NUMBER = 4;
    private boolean hasRpcVersion;
    private java.lang.String rpcVersion_ = "";
    public boolean hasRpcVersion() { return hasRpcVersion; }
    public java.lang.String getRpcVersion() { return rpcVersion_; }
    
    // optional int32 timeout = 5;
    public static final int TIMEOUT_FIELD_NUMBER = 5;
    private boolean hasTimeout;
    private int timeout_ = 0;
    public boolean hasTimeout() { return hasTimeout; }
    public int getTimeout() { return timeout_; }
    
    // optional string serviceName = 6;
    public static final int SERVICENAME_FIELD_NUMBER = 6;
    private boolean hasServiceName;
    private java.lang.String serviceName_ = "";
    public boolean hasServiceName() { return hasServiceName; }
    public java.lang.String getServiceName() { return serviceName_; }
    
    // optional string methodName = 7;
    public static final int METHODNAME_FIELD_NUMBER = 7;
    private boolean hasMethodName;
    private java.lang.String methodName_ = "";
    public boolean hasMethodName() { return hasMethodName; }
    public java.lang.String getMethodName() { return methodName_; }
    
    // optional bytes parameters = 8;
    public static final int PARAMETERS_FIELD_NUMBER = 8;
    private boolean hasParameters;
    private com.google.protobuf.ByteString parameters_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasParameters() { return hasParameters; }
    public com.google.protobuf.ByteString getParameters() { return parameters_; }
    
    // optional string paramClassName = 9;
    public static final int PARAMCLASSNAME_FIELD_NUMBER = 9;
    private boolean hasParamClassName;
    private java.lang.String paramClassName_ = "";
    public boolean hasParamClassName() { return hasParamClassName; }
    public java.lang.String getParamClassName() { return paramClassName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessageType) return false;
      if (!hasTransferId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageType()) {
        output.writeInt32(1, getMessageType());
      }
      if (hasCallType()) {
        output.writeInt32(2, getCallType());
      }
      if (hasTransferId()) {
        output.writeInt64(3, getTransferId());
      }
      if (hasRpcVersion()) {
        output.writeString(4, getRpcVersion());
      }
      if (hasTimeout()) {
        output.writeInt32(5, getTimeout());
      }
      if (hasServiceName()) {
        output.writeString(6, getServiceName());
      }
      if (hasMethodName()) {
        output.writeString(7, getMethodName());
      }
      if (hasParameters()) {
        output.writeBytes(8, getParameters());
      }
      if (hasParamClassName()) {
        output.writeString(9, getParamClassName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMessageType());
      }
      if (hasCallType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getCallType());
      }
      if (hasTransferId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTransferId());
      }
      if (hasRpcVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getRpcVersion());
      }
      if (hasTimeout()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getTimeout());
      }
      if (hasServiceName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getServiceName());
      }
      if (hasMethodName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getMethodName());
      }
      if (hasParameters()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getParameters());
      }
      if (hasParamClassName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getParamClassName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasCallType()) {
          setCallType(other.getCallType());
        }
        if (other.hasTransferId()) {
          setTransferId(other.getTransferId());
        }
        if (other.hasRpcVersion()) {
          setRpcVersion(other.getRpcVersion());
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        if (other.hasServiceName()) {
          setServiceName(other.getServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasParameters()) {
          setParameters(other.getParameters());
        }
        if (other.hasParamClassName()) {
          setParamClassName(other.getParamClassName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMessageType(input.readInt32());
              break;
            }
            case 16: {
              setCallType(input.readInt32());
              break;
            }
            case 24: {
              setTransferId(input.readInt64());
              break;
            }
            case 34: {
              setRpcVersion(input.readString());
              break;
            }
            case 40: {
              setTimeout(input.readInt32());
              break;
            }
            case 50: {
              setServiceName(input.readString());
              break;
            }
            case 58: {
              setMethodName(input.readString());
              break;
            }
            case 66: {
              setParameters(input.readBytes());
              break;
            }
            case 74: {
              setParamClassName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 messageType = 1;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public int getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(int value) {
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = 0;
        return this;
      }
      
      // optional int32 callType = 2;
      public boolean hasCallType() {
        return result.hasCallType();
      }
      public int getCallType() {
        return result.getCallType();
      }
      public Builder setCallType(int value) {
        result.hasCallType = true;
        result.callType_ = value;
        return this;
      }
      public Builder clearCallType() {
        result.hasCallType = false;
        result.callType_ = 0;
        return this;
      }
      
      // required int64 transferId = 3;
      public boolean hasTransferId() {
        return result.hasTransferId();
      }
      public long getTransferId() {
        return result.getTransferId();
      }
      public Builder setTransferId(long value) {
        result.hasTransferId = true;
        result.transferId_ = value;
        return this;
      }
      public Builder clearTransferId() {
        result.hasTransferId = false;
        result.transferId_ = 0L;
        return this;
      }
      
      // optional string rpcVersion = 4;
      public boolean hasRpcVersion() {
        return result.hasRpcVersion();
      }
      public java.lang.String getRpcVersion() {
        return result.getRpcVersion();
      }
      public Builder setRpcVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRpcVersion = true;
        result.rpcVersion_ = value;
        return this;
      }
      public Builder clearRpcVersion() {
        result.hasRpcVersion = false;
        result.rpcVersion_ = getDefaultInstance().getRpcVersion();
        return this;
      }
      
      // optional int32 timeout = 5;
      public boolean hasTimeout() {
        return result.hasTimeout();
      }
      public int getTimeout() {
        return result.getTimeout();
      }
      public Builder setTimeout(int value) {
        result.hasTimeout = true;
        result.timeout_ = value;
        return this;
      }
      public Builder clearTimeout() {
        result.hasTimeout = false;
        result.timeout_ = 0;
        return this;
      }
      
      // optional string serviceName = 6;
      public boolean hasServiceName() {
        return result.hasServiceName();
      }
      public java.lang.String getServiceName() {
        return result.getServiceName();
      }
      public Builder setServiceName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceName = true;
        result.serviceName_ = value;
        return this;
      }
      public Builder clearServiceName() {
        result.hasServiceName = false;
        result.serviceName_ = getDefaultInstance().getServiceName();
        return this;
      }
      
      // optional string methodName = 7;
      public boolean hasMethodName() {
        return result.hasMethodName();
      }
      public java.lang.String getMethodName() {
        return result.getMethodName();
      }
      public Builder setMethodName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMethodName = true;
        result.methodName_ = value;
        return this;
      }
      public Builder clearMethodName() {
        result.hasMethodName = false;
        result.methodName_ = getDefaultInstance().getMethodName();
        return this;
      }
      
      // optional bytes parameters = 8;
      public boolean hasParameters() {
        return result.hasParameters();
      }
      public com.google.protobuf.ByteString getParameters() {
        return result.getParameters();
      }
      public Builder setParameters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasParameters = true;
        result.parameters_ = value;
        return this;
      }
      public Builder clearParameters() {
        result.hasParameters = false;
        result.parameters_ = getDefaultInstance().getParameters();
        return this;
      }
      
      // optional string paramClassName = 9;
      public boolean hasParamClassName() {
        return result.hasParamClassName();
      }
      public java.lang.String getParamClassName() {
        return result.getParamClassName();
      }
      public Builder setParamClassName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasParamClassName = true;
        result.paramClassName_ = value;
        return this;
      }
      public Builder clearParamClassName() {
        result.hasParamClassName = false;
        result.paramClassName_ = getDefaultInstance().getParamClassName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      com.dianping.dpsf.protocol.protobuf.DPSFProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.Request)
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {
      initFields();
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.dpsf.protocol.protobuf.DPSFProtos.internal_static_com_dianping_dpsf_protocol_protobuf_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.dpsf.protocol.protobuf.DPSFProtos.internal_static_com_dianping_dpsf_protocol_protobuf_Response_fieldAccessorTable;
    }
    
    // required int32 messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private boolean hasMessageType;
    private int messageType_ = 0;
    public boolean hasMessageType() { return hasMessageType; }
    public int getMessageType() { return messageType_; }
    
    // required int64 transferId = 2;
    public static final int TRANSFERID_FIELD_NUMBER = 2;
    private boolean hasTransferId;
    private long transferId_ = 0L;
    public boolean hasTransferId() { return hasTransferId; }
    public long getTransferId() { return transferId_; }
    
    // optional string rpcVersion = 3;
    public static final int RPCVERSION_FIELD_NUMBER = 3;
    private boolean hasRpcVersion;
    private java.lang.String rpcVersion_ = "";
    public boolean hasRpcVersion() { return hasRpcVersion; }
    public java.lang.String getRpcVersion() { return rpcVersion_; }
    
    // optional bytes return = 4;
    public static final int RETURN_FIELD_NUMBER = 4;
    private boolean hasReturn;
    private com.google.protobuf.ByteString return_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasReturn() { return hasReturn; }
    public com.google.protobuf.ByteString getReturn() { return return_; }
    
    // optional string cause = 5;
    public static final int CAUSE_FIELD_NUMBER = 5;
    private boolean hasCause;
    private java.lang.String cause_ = "";
    public boolean hasCause() { return hasCause; }
    public java.lang.String getCause() { return cause_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessageType) return false;
      if (!hasTransferId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessageType()) {
        output.writeInt32(1, getMessageType());
      }
      if (hasTransferId()) {
        output.writeInt64(2, getTransferId());
      }
      if (hasRpcVersion()) {
        output.writeString(3, getRpcVersion());
      }
      if (hasReturn()) {
        output.writeBytes(4, getReturn());
      }
      if (hasCause()) {
        output.writeString(5, getCause());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessageType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMessageType());
      }
      if (hasTransferId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTransferId());
      }
      if (hasRpcVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getRpcVersion());
      }
      if (hasReturn()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getReturn());
      }
      if (hasCause()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getCause());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response result;
      
      // Construct using com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response();
        return builder;
      }
      
      protected com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.getDescriptor();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response getDefaultInstanceForType() {
        return com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response) {
          return mergeFrom((com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response other) {
        if (other == com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTransferId()) {
          setTransferId(other.getTransferId());
        }
        if (other.hasRpcVersion()) {
          setRpcVersion(other.getRpcVersion());
        }
        if (other.hasReturn()) {
          setReturn(other.getReturn());
        }
        if (other.hasCause()) {
          setCause(other.getCause());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMessageType(input.readInt32());
              break;
            }
            case 16: {
              setTransferId(input.readInt64());
              break;
            }
            case 26: {
              setRpcVersion(input.readString());
              break;
            }
            case 34: {
              setReturn(input.readBytes());
              break;
            }
            case 42: {
              setCause(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 messageType = 1;
      public boolean hasMessageType() {
        return result.hasMessageType();
      }
      public int getMessageType() {
        return result.getMessageType();
      }
      public Builder setMessageType(int value) {
        result.hasMessageType = true;
        result.messageType_ = value;
        return this;
      }
      public Builder clearMessageType() {
        result.hasMessageType = false;
        result.messageType_ = 0;
        return this;
      }
      
      // required int64 transferId = 2;
      public boolean hasTransferId() {
        return result.hasTransferId();
      }
      public long getTransferId() {
        return result.getTransferId();
      }
      public Builder setTransferId(long value) {
        result.hasTransferId = true;
        result.transferId_ = value;
        return this;
      }
      public Builder clearTransferId() {
        result.hasTransferId = false;
        result.transferId_ = 0L;
        return this;
      }
      
      // optional string rpcVersion = 3;
      public boolean hasRpcVersion() {
        return result.hasRpcVersion();
      }
      public java.lang.String getRpcVersion() {
        return result.getRpcVersion();
      }
      public Builder setRpcVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRpcVersion = true;
        result.rpcVersion_ = value;
        return this;
      }
      public Builder clearRpcVersion() {
        result.hasRpcVersion = false;
        result.rpcVersion_ = getDefaultInstance().getRpcVersion();
        return this;
      }
      
      // optional bytes return = 4;
      public boolean hasReturn() {
        return result.hasReturn();
      }
      public com.google.protobuf.ByteString getReturn() {
        return result.getReturn();
      }
      public Builder setReturn(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReturn = true;
        result.return_ = value;
        return this;
      }
      public Builder clearReturn() {
        result.hasReturn = false;
        result.return_ = getDefaultInstance().getReturn();
        return this;
      }
      
      // optional string cause = 5;
      public boolean hasCause() {
        return result.hasCause();
      }
      public java.lang.String getCause() {
        return result.getCause();
      }
      public Builder setCause(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCause = true;
        result.cause_ = value;
        return this;
      }
      public Builder clearCause() {
        result.hasCause = false;
        result.cause_ = getDefaultInstance().getCause();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.dianping.dpsf.protocol.protobuf.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      com.dianping.dpsf.protocol.protobuf.DPSFProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.dianping.dpsf.protocol.protobuf.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dianping_dpsf_protocol_protobuf_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dianping_dpsf_protocol_protobuf_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndpsf.proto\022#com.dianping.dpsf.protocol" +
      ".protobuf\"\276\001\n\007Request\022\023\n\013messageType\030\001 \002" +
      "(\005\022\020\n\010callType\030\002 \001(\005\022\022\n\ntransferId\030\003 \002(\003" +
      "\022\022\n\nrpcVersion\030\004 \001(\t\022\017\n\007timeout\030\005 \001(\005\022\023\n" +
      "\013serviceName\030\006 \001(\t\022\022\n\nmethodName\030\007 \001(\t\022\022" +
      "\n\nparameters\030\010 \001(\014\022\026\n\016paramClassName\030\t \001" +
      "(\t\"f\n\010Response\022\023\n\013messageType\030\001 \002(\005\022\022\n\nt" +
      "ransferId\030\002 \002(\003\022\022\n\nrpcVersion\030\003 \001(\t\022\016\n\006r" +
      "eturn\030\004 \001(\014\022\r\n\005cause\030\005 \001(\tB1\n#com.dianpi" +
      "ng.dpsf.protocol.protobufB\nDPSFProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dianping_dpsf_protocol_protobuf_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dianping_dpsf_protocol_protobuf_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_Request_descriptor,
              new java.lang.String[] { "MessageType", "CallType", "TransferId", "RpcVersion", "Timeout", "ServiceName", "MethodName", "Parameters", "ParamClassName", },
              com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.class,
              com.dianping.dpsf.protocol.protobuf.DPSFProtos.Request.Builder.class);
          internal_static_com_dianping_dpsf_protocol_protobuf_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dianping_dpsf_protocol_protobuf_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dianping_dpsf_protocol_protobuf_Response_descriptor,
              new java.lang.String[] { "MessageType", "TransferId", "RpcVersion", "Return", "Cause", },
              com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.class,
              com.dianping.dpsf.protocol.protobuf.DPSFProtos.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
